### ISSUE TITLE
Uncaught ReferenceError: error is not defined

### ISSUE THREAD

**Issue by AGulev** [yahuaru/atom-dbg-lua#1]
[Enter steps to reproduce:]

1.Run debug session
2. Debug anonymous function here: 

    dirtylarry:button("set_window_title", action_id, action, function ()
    	defos.set_window_title(tostring(self.input_title))
    end)

example project:
https://github.com/AGulev/defos

**Atom**: 1.21.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [dbg-lua](https://github.com/yahuaru/atom-dbg-lua) package 0.3.0

### Stack Trace

Uncaught ReferenceError: error is not defined

```
At /Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:113

ReferenceError: error is not defined
    at stderr (/packages/dbg-lua/lib/mobdebug.coffee:113:45)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:212:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

### Commands

```
     -1:06.5.0 dbg:pause-continue (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
autocomplete-lua 0.9.0 
busy-signal 1.4.3 
dbg 1.6.2 
dbg-lua 0.3.0 
defold-ide 0.3.1 
goto 1.8.3 
indent-guide-improved 1.4.13 
intentions 1.1.5 
language-lua 0.9.11 
linter 2.2.0 
linter-lua 1.0.4 
linter-luacheck 2.0.1 
linter-ui-default 1.6.10 
```

**Comment by AGulev** [comment]
IntersectionObserver.observe(target): target element is not a descendant of root.
TreeView @ <embedded>:118131
mobdebug.coffee [sm]:56 CONNECTED: 127.0.0.1:53952
mobdebug.coffee [sm]:124 setb /example/example.script 20
mobdebug.coffee [sm]:68 DATA 127.0.0.1:53952 200 OK

mobdebug.coffee [sm]:124 run 
mobdebug.coffee [sm]:68 DATA 127.0.0.1:53952 200 OK

mobdebug.coffee [sm]:124 delb /example/example.script 20
mobdebug.coffee [sm]:124 setb /example/example.gui_script 19
mobdebug.coffee [sm]:68 DATA 127.0.0.1:53952 202 Paused /example/example.gui_script 19

mobdebug.coffee [sm]:124 stack 
mobdebug.coffee [sm]:68 DATA 127.0.0.1:53952 200 OK do local _={{{"cb","/example/example.gui_script",18,19,"Lua","local","/example/example.gui_script"},{},{self={"GuiScript: 0x08993f80","GuiScript: 0x08993f80"}}},{{"button","/dirtylarry/dirtylarry.lua",57,67,"Lua","method","/dirtylarry/dirtylarry.lua"},{hit={true,"true"},self={{hit=function() --[[..skipped..]] end,scrollarea=function() --[[..skipped..]] end,utf8_gfind="([%z\1-\127�-�][�-�]*)",is_enabled=function() --[[..skipped..]] end,colors={active="vmath.vector4(1, 1, 1, 1)",base="vmath.vector4(1, 1, 1, 1)",enabled="vmath.vector4(1, 1, 1, 1)",disabled="vmath.vector4(1, 1, 1, 0.20000000298023)",mark="vmath.vector4(1, 0.15686275064945, 0.15686275064945, 1)"},action_id_touch="hash: [touch]",input=function() --[[..skipped..]] end,radio=function() --[[..skipped..]] end,action_id_backspace="hash: [backspace]",button=function() --[[..skipped..]] end,checkbox=function() --[[..skipped..]] end,input_nodes={["hash: [default]2159aaae9b4691780afe7af48a12c147window_title"]={active=false,data="Empty",id="window_title"}},action_id_marked_text="hash: [marked_text]",active_input_marked="",action_id_text="hash: [text]"},"table: 0x0804a240"},node={"set_window_title","set_window_title"},cb={function() --[[..skipped..]] end,"function: 0x089921a0"},node_bg={"box@(790, 590, 0)","box@(790, 590, 0)"},label_p={"vmath.vector3(0, 0, 0)","vmath.vector3(0, 0, 0)"},node_label={"Set Window Title@(0, -2, 0)","Set Window Title@(0, -2, 0)"},flipbook={"button_normal","button_normal"},action={{x=867.5,pressed=false,y=579.5,screen_y=580,screen_dy=0,screen_dx=0,screen_x=867,dx=0,value=0,repeated=false,released=true,dy=0},"table: 0x0b7f4ba0"},action_id={nil,"hash: [touch]"}},{hit_test={function() --[[..skipped..]] end,"function: 0x0804cc70"}}},{{nil,"/example/example.gui_script",15,18,"Lua","","/example/example.gui_script"},{self={nil,"GuiScript: 0x08993f80"},action={nil,"table: 0x0b7f4ba0"},action_id={nil,"hash: [touch]"}},{dirtylarry={nil,"table: 0x0804a240"},change_mouse_label={function() --[[..skipped..]] end,"function: 0x08992420"}}}};local __={};_[2][2].action_id[1]=_[2][2].self[1].action_id_touch;_[3][2].self[1]=_[1][3].self[1];_[3][2].action[1]=_[2][2].action[1];_[3][2].action_id[1]=_[2][2].self[1].action_id_touch;_[3][3].dirtylarry[1]=_[2][2].self[1];return _;end

mobdebug.coffee [sm]:113 Uncaught ReferenceError: error is not defined
    at stderr (/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:113:45)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:212:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
mobdebug.coffee [sm]:113 Uncaught ReferenceError: error is not defined
    at stderr (/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:113:45)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:219:40)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
mobdebug.coffee [sm]:124 delb /example/example.gui_script 19
mobdebug.coffee [sm]:68 DATA 127.0.0.1:53952 200 OK

mobdebug.coffee [sm]:124 run 
mobdebug.coffee [sm]:68 DATA 127.0.0.1:53952 200 OK

mobdebug.coffee [sm]:124 setb /example/example.script 20
mobdebug.coffee [sm]:124 done 
mobdebug.coffee [sm]:61 CLOSED: 127.0.0.1:53952
mobdebug.coffee [sm]:56 CONNECTED: 127.0.0.1:54219
mobdebug.coffee [sm]:124 setb /example/example.script 20
mobdebug.coffee [sm]:68 DATA 127.0.0.1:54219 200 OK

mobdebug.coffee [sm]:124 run 
mobdebug.coffee [sm]:68 DATA 127.0.0.1:54219 200 OK

mobdebug.coffee [sm]:124 setb /example/example.gui_script 12
2beautifier.coffee [sm]:27 WARNING: negative indentation at line 64: end
mobdebug.coffee [sm]:68 DATA 127.0.0.1:54219 202 Paused /example/example.gui_script 12

/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:196 stack 
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:84 DATA 127.0.0.1:54219 200 OK do local _={{{"change_mouse_label","/example/example.gui_script",10,12,"Lua","upvalue","/example/example.gui_script"},{label={"Disable mouse cursor@(0, -2, 0)","Disable mouse cursor@(0, -2, 0)"},text={"Enable mouse cursor","Enable mouse cursor"}},{}},{{"cb","/example/example.gui_script",51,55,"Lua","local","/example/example.gui_script"},{},{change_mouse_label={function() --[[..skipped..]] end,"function: 0x0860c420"},self={"GuiScript: 0x0860df80","GuiScript: 0x0860df80"}}},{{"button","/dirtylarry/dirtylarry.lua",57,67,"Lua","method","/dirtylarry/dirtylarry.lua"},{hit={true,"true"},self={{hit=function() --[[..skipped..]] end,scrollarea=function() --[[..skipped..]] end,utf8_gfind="([%z\1-\127�-�][�-�]*)",is_enabled=function() --[[..skipped..]] end,colors={active="vmath.vector4(1, 1, 1, 1)",base="vmath.vector4(1, 1, 1, 1)",enabled="vmath.vector4(1, 1, 1, 1)",disabled="vmath.vector4(1, 1, 1, 0.20000000298023)",mark="vmath.vector4(1, 0.15686275064945, 0.15686275064945, 1)"},action_id_touch="hash: [touch]",input=function() --[[..skipped..]] end,radio=function() --[[..skipped..]] end,action_id_backspace="hash: [backspace]",button=function() --[[..skipped..]] end,checkbox=function() --[[..skipped..]] end,input_nodes={["hash: [default]2159aaae9b4691780afe7af48a12c147window_title"]={active=false,data="Empty",id="window_title"}},action_id_marked_text="hash: [marked_text]",active_input_marked="",action_id_text="hash: [text]"},"table: 0x07cc4240"},node={"disable_mouse_cursor","disable_mouse_cursor"},cb={function() --[[..skipped..]] end,"function: 0x08616c50"},node_bg={"box@(165, 370, 0)","box@(165, 370, 0)"},label_p={"vmath.vector3(0, 0, 0)","vmath.vector3(0, 0, 0)"},node_label={"Disable mouse cursor@(0, -2, 0)","Disable mouse cursor@(0, -2, 0)"},flipbook={"button_normal","button_normal"},action={{x=221.5,pressed=false,y=370.5,screen_y=371,screen_dy=0,screen_dx=0,screen_x=221,dx=0,value=0,repeated=false,released=true,dy=0},"table: 0x07cc8230"},action_id={nil,"hash: [touch]"}},{hit_test={function() --[[..skipped..]] end,"function: 0x07cc6c70"}}},{{nil,"/example/example.gui_script",15,51,"Lua","","/example/example.gui_script"},{self={nil,"GuiScript: 0x0860df80"},action={nil,"table: 0x07cc8230"},action_id={nil,"hash: [touch]"}},{dirtylarry={nil,"table: 0x07cc4240"},change_mouse_label={nil,"function: 0x0860c420"}}}};local __={};_[3][2].action_id[1]=_[3][2].self[1].action_id_touch;_[4][2].self[1]=_[2][3].self[1];_[4][2].action[1]=_[3][2].action[1];_[4][2].action_id[1]=_[3][2].self[1].action_id_touch;_[4][3].dirtylarry[1]=_[3][2].self[1];_[4][3].change_mouse_label[1]=_[2][3].change_mouse_label[1];return _;end

/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:168 Uncaught ReferenceError: error is not defined
    at stderr (/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:113:45)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:212:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:168 Uncaught ReferenceError: error is not defined
    at stderr (/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:113:45)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:219:40)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:196 delb /example/example.gui_script 12
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:84 DATA 127.0.0.1:54219 200 OK

/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:196 done 
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:73 CLOSED: 127.0.0.1:54219
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:69 CONNECTED: 127.0.0.1:54272
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:196 setb /example/example.script 20
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:84 DATA 127.0.0.1:54272 200 OK

/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:196 run 
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:84 DATA 127.0.0.1:54272 200 OK

/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:196 setb /example/example.gui_script 63
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:84 DATA 127.0.0.1:54272 202 Paused /example/example.gui_script 63

/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:196 stack 
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:84 DATA 127.0.0.1:54272 200 OK do local _={{{nil,"/example/example.gui_script",15,63,"Lua","","/example/example.gui_script"},{self={"GuiScript: 0x12d37f80","GuiScript: 0x12d37f80"},action={{screen_dy=-3,x=27.5,screen_x=27,dx=27,y=764.5,screen_y=765,screen_dx=27,dy=-3},"table: 0x123f97f0"},action_id={nil,"nil"}},{dirtylarry={{hit=function() --[[..skipped..]] end,scrollarea=function() --[[..skipped..]] end,utf8_gfind="([%z\1-\127�-�][�-�]*)",is_enabled=function() --[[..skipped..]] end,colors={active="vmath.vector4(1, 1, 1, 1)",base="vmath.vector4(1, 1, 1, 1)",enabled="vmath.vector4(1, 1, 1, 1)",disabled="vmath.vector4(1, 1, 1, 0.20000000298023)",mark="vmath.vector4(1, 0.15686275064945, 0.15686275064945, 1)"},action_id_touch="hash: [touch]",input=function() --[[..skipped..]] end,radio=function() --[[..skipped..]] end,action_id_backspace="hash: [backspace]",button=function() --[[..skipped..]] end,checkbox=function() --[[..skipped..]] end,input_nodes={["hash: [default]2159aaae9b4691780afe7af48a12c147window_title"]={active=false,data="Empty",id="window_title"}},action_id_marked_text="hash: [marked_text]",active_input_marked="",action_id_text="hash: [text]"},"table: 0x123ee240"},change_mouse_label={function() --[[..skipped..]] end,"function: 0x12d36420"}}}};return _;end

/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:168 Uncaught ReferenceError: error is not defined
    at stderr (/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:113:45)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:212:17)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:168 Uncaught ReferenceError: error is not defined
    at stderr (/Users/alexeygulev/.atom/packages/dbg-lua/lib/mobdebug.coffee:113:45)
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:219:40)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
